const Action = {
  Enter: "enter",
  Exit: "exit",
  Look: "look at",
  Inspect: "inspect",
  Walk: "walk",
  Take: "take",
  Drop: "drop",
  Use: "use",
  Open: "open",
  Close: "close",
  Talk: "talk to",
  Attack: "attack",
  Inventory: "inventory",
  Help: "help",
  Clear: "clear",
};
